#logger:
#  level: debug
logger:
  development: 
    level: debug
    transport: 
      target: 'pino-pretty'
      options: 
        translateTime: 'HH:MM:ss Z'
        ignore: 'pid,hostname'
  production: true
  local: false

mongo:
  url: mongodb://10.234.20.50:32770/test
  #url: mongodb://192.168.1.21:27017/test
  #url: mongodb://10.234.20.77:27017/test
  databaseName: test
  debug: false

redis:
  enable: false
  url: redis://10.234.20.77:6379

server:
  host: localhost
  port: 3000
  repository: 
    path: /Users/ajmarmar/Documents/Proyectos/ApiSeedlingTS/repository
    maxFile: 250
    compress: true
    noCompress:
      - tar
      - tar.gz
      - zip
      - rar
      - 7z
    limits:
      fileSize: 10485760
      files: 10
  secure:
    secretJWT: mi secret
    tokenExpirationTime: 2h
    unprotected:
      - POST:/v1/session/login
      - POST:/v1/session/logout
      - POST:/v1/session/register
      - GET:/api_docs/*
      - GET:/favicon.ico
      - GET:/swagger-ui/*
      - GET:/spec